tasks:
  - prebuild: mvn install spring-boot:start spring-boot:stop -DskipTests
    command: mvn spring-boot:run
  - init: mysql < DDL.sql
image: gitpod/workspace-mysql

ports:
  - port: 8080
    onOpen: open-preview
github:
  prebuilds:
    master: true